### ISSUE TITLE
Invoking retext with a filename from the command line does not open the file

### ISSUE THREAD

**Issue by callegar** [retext-project/retext#606] opened 2023-01-12 10:42 UTC
If you have retext already running, with a file open (say `file_a.md`) and you enter on the command line `retext file_b.md`, retext does not open a new tab with the new file as it would be expected.

**Comment by mitya57** [comment] 2023-01-12 13:04
This is probably a duplicate of #594, which was fixed in 6f6e5f3ab48289b03fe8256f24a347e876d94fd1.

As a workaround, use absolute paths.

**Closed** 2023-01-12 13:04 UTC
