### ISSUE TITLE
Opened file becomes "New document" after a short time

### ISSUE THREAD

**Issue by damonlynch** [retext-project/retext#208] opened 2016-05-17 09:39 UTC
I'm using ReText 6.0.0 (using PyMarkups 2.0.0) on Ubuntu 16.04 installed via pip.

Problem: open an rst file. Wait a minute or so. Retext forgets that it was an opened file, and therefore treats it like a brand new file that was never saved before.

**Comment by frantic1048** [comment] 2016-05-17 10:18
Very similarly issue here: 

1. open an existing rst file
2. operate on it a while
3. the title bar and tab title become "new document". It also performs like a new doc when saving.

I've looked into terminal output but nothing looks related to this issue.

Here's a sample output: http://codepad.org/X5Fj0bsC, Open an rst file, operate a while, the issue happens, then close ReText.

**Comment by Griffon26** [comment] 2016-05-17 20:20
Dmitry and I are unable to reproduce this problem. Can you give us more specifics?
Even moving the mouse or switching focus can make a difference, so it could be helpful to know if it occurs even when you're not doing anything with mouse/keyboard.
How long after opening the application does it happen? Does it always take exactly this long?

**Comment by frantic1048** [comment] 2016-05-18 04:53
![retext_newdoc_issue](https://cloud.githubusercontent.com/assets/3102803/15347725/df582624-1cf6-11e6-8907-6adbcbfa1157.gif)

Here's a full process recording:

1. open ReText
2. open an rst file
3. just wait about 40s, the issue happens

**Comment by damonlynch** [comment] 2016-05-18 04:53
The time it takes is inconsistent - I tried it two time just now. One was less than 18 seconds and the other 39 seconds. I wasn't using the mouse or doing anything.

**Comment by Griffon26** [comment] 2016-05-19 19:17
I just pushed a new branch called "newdoc". Could either one of you run that version and attach the output to this issue? I should be able to recognize the occurrence of the problem in the trace.

For instance:

    ./retext.py | tee trace.txt

**Comment by frantic1048** [comment] 2016-05-20 06:34
Here's a log running from **newdoc** branch, open an rst file and do nothing (even not opening preview), seconds after the issue happens.
http://codepad.org/gQN0s0yu

**Comment by frantic1048** [comment] 2016-05-20 06:40
Sorry, the log is too large(2.8MiB) and codepad clamped the content.

I paste it on gist, it's complete now:
https://gist.github.com/frantic1048/d2cd1fb9ca8799bc1e56fe839354e427

**Comment by Griffon26** [comment] 2016-05-20 15:48
I was able to reproduce the problem when I noticed in the trace that auto-save was enabled. The fix was just committed to the master branch.

Thanks for helping me debug this!

**Closed by Griffon26** 2016-05-20 15:48 UTC
