### ISSUE TITLE
[FR] Reuse existing window/instance when opening files in file manager

### ISSUE THREAD

**Issue by N46AN** [retext-project/retext#401] opened 2018-10-15 16:54 UTC
OS: Debian 9
ReText: 6.0.2

Step to reproduce:
1. Open a file with ReText;
2. In the OS/DE filemanager, such as nautilus/dolphin/thunar, open another file with ReText.

Actual behaviour:
Step 2 creates a new window and instance of ReText.

Expected behaviour:
Step 2 should reuse the existing window and instance created in step 1.

**Comment by mitya57** [comment] 2018-10-15 18:06
This is a duplicate of #148. It will be non-trivial to implement, and pull requests are welcome.

**Comment by mitya57** [comment] 2019-10-14 08:21
This is now fixed in master branch (see #476). Any feedback is appreciated.

**Closed by mitya57** 2019-10-14 08:21 UTC
