### ISSUE TITLE
Any chance of ReText officially supporting windows? 

### ISSUE THREAD

**Issue by ghost** [retext-project/retext#558] opened 2021-05-15 20:54 UTC
I realize Windows is not officially supported. 

- Windows is widely used for desktop and ReText being Linux only prevent a huge user base from using this awesome piece of software, I know it work on Windows with some hacks here and there but it's still not officially supported nor it work in full mode/power. 
- Also both QT and Python are cross-platform so there shouldn't be a problem to support Windows or even both Windows and macOS.

**Comment by mitya57** [comment] 2021-05-17 13:54
Hi!

Installing ReText on Windows has become very easy during the last years. All you need is having Python and running `pip install ReText` (just like on other platforms).

Windows is a supported platform, and the docs say it is not *officially* supported just because I am not using Windows myself so I cannot test every release there to make sure that everything works fine. However, it *should* still work fine because, as you say, both Qt and Python are cross-platform. The same applies to macOS and other platforms that I don’t use.

You say that it needs hacks and does not work in full mode. Can you please explain what you mean? If there are any particular issues, reports about them are welcome — I will see what I can do.

**Comment by matkoniecz** [comment] 2021-05-28 15:14
Pinging @Shen897 

> You say that it needs hacks and does not work in full mode. Can you please explain what you mean? If there are any particular issues, reports about them are welcome — I will see what I can do.

**Comment by szpeter80** [comment] 2022-11-01 15:31
I have just tried right now, and i can confirm, Retext do install and work on Windows 10 (tried and tested on 2 different x86 64bit machines, one physical, one is a vm).

Install steps:

1 - open console (cmd), type "python"
2 - if python is not installed, it will lead you to the ms app store and you can install from there. AFAIK the python installed this way is fully supported by core python team, the version is fairly recent (3.11 was just released, the installed version says "Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32".
3 - you can create a venv with "python -m venv .\project-venv". Beware, its windows so look out for backslashes. Venv activation is done be executing '.\project-venv\Scripts\activate.bat'
4 - in the venv, type 'pip install retext', and a few minutes later install is complete
5 - you can launch retext by typing "retext", or you can find a binary under ".\project-venv\Scripts\retext.exe"

The only "hack" is needed, that if a directory has a space in its name, and it happens to be the python install directory, the wrapper scripts probably breaks and when you type retext at the command line, you get the prompt back. The solution is to create a directory path w/o spaces like "C:\retext" and do the install there. It seems to me it is specific to the python windows port, rather than retext itself, maybe a short mention in the docs would be useful for some users.

**Comment by sergeevabc** [comment] 2024-01-21 12:17
There are ways to bundle a Python-based project as a standalone executable for Windows ([yt-dlp](https://github.com/yt-dlp/yt-dlp) is a famous example), it's just that it hasn't been seriously considered here.

**Comment by clach04** [comment] 2024-07-26 15:00
Recommend closing this issue as complete

**Comment by szpeter80** [comment] 2024-07-26 15:44
Agree, i use it regularly on w11 and just works fine.

**Closed** 2024-07-26 16:03 UTC
