### ISSUE TITLE
Add as new tab when opening a new file in the opened instance

### ISSUE THREAD

**Issue by Mte90** [retext-project/retext#471] opened 2019-09-11 14:55 UTC
Right now when I open a markdown file open a new instance of retext instead open a new tab.
There is a way to avoid that?

**Comment by mitya57** [comment] 2019-09-11 15:41
This is a difficult task and I do not have resources to work on it. Patches are welcome.

I am closing this as this is a duplicate of #148.

**Closed by mitya57** 2019-09-11 15:41 UTC
