### ISSUE TITLE
Keyboard shortcut for finding text doesn't work

### ISSUE THREAD

**Issue by colans** [retext-project/retext#159] opened 2015-10-08 22:58 UTC
On Ubuntu, Ctrl-F doesn't actually do anything.  It's necessary to use the menu to navigate to Edit -> Find text for searching.

**Comment by mitya57** [comment] 2015-10-09 14:16
Works fine for me. Do other shortcuts work? Is the keybinding (Ctrl+F) displayed near Find item in the menu?

**Comment by colans** [comment] 2015-10-09 15:05
Yes, I just tested with Ctrl-N and Ctrl-O and they both work.  The keybinding is displayed in the menu.  Seems like it's the only one (that I've tried) that doesn't work.

**Comment by mitya57** [comment] 2015-10-09 15:13
If you are using Unity, can you try running ReText as `UBUNTU_MENUPROXY=0 retext` and see if the bug persists?

I suspect that the global menu can break this stuff.

**Comment by mitya57** [comment] 2016-04-04 22:02
Closing because of no feedback.

**Comment by colans** [comment] 2016-04-05 14:52
Sorry, I didn't get back to you soon enough.  The bug goes away with that command prefix so your theory is correct.

Looks like I can comment, but can't reopen this ticket so please do that on my behalf.

**Comment by mitya57** [comment] 2016-04-05 20:42
Reopened, though I don't think anything can really be done in ReText about this…

**Comment by colans** [comment] 2016-04-05 22:18
To work around the issue, I've added this alias to my .zshrc file:
* alias retext='UBUNTU_MENUPROXY=0 \retext'

If this is being caused by an upstream bug, do you know the URL?

**Comment by mitya57** [comment] 2016-04-06 20:13
I think the problem is that Qt only creates shortcuts for actions that are somehow visible to user (by design). When global menu is used, the actions are not visible (from Qt point of view), but rather exported over D-Bus, so no shortcuts for them are created.

We can't blame Ubuntu's global menu implementation (appmenu-qt5) for that: even when Qt's own implementation (from Qt 5.6) is used, I believe it will have the same problem.

**Comment by zuernBernhard** [comment] 2016-08-23 09:23
I'm also affected on Ubuntu 16.04 64bit. How can we solve it ?

**Comment by mitya57** [comment] 2016-08-26 18:46
@zuernBernhard You can use the workaround suggested in https://github.com/retext-project/retext/issues/159#issuecomment-206007744: start ReText with `UBUNTU_MENUPROXY=0` set.

**Comment by zuernBernhard** [comment] 2016-08-29 06:56
Works ! - Is it possible to get that into the Ubuntu-Package ?

**Comment by mitya57** [comment] 2016-08-29 07:25
That's just a workaround, not a proper fix (because it breaks global menu integration). So it's impossible to get that into Ubuntu package…

Maybe it will be resolved in Ubuntu 16.10 though, where appmenu-qt5 will be removed from default installations and replaced by Qt code for global menu. (I have not yet tested whether the shortcuts work with that configuration).

**Comment by MrksKwsnck** [comment] 2017-03-12 15:13
I just ran into the same issue with a freshly installed Ubuntu 16.04 LTS and ReText 7.0.0 via pip. Unfortunately the provided workaround to run ReText with that environment variable

    $ UBUNTU_MENUPROXY=0 retext

does not work for me. Any suggestions?

**Comment by MrksKwsnck** [comment] 2017-03-12 15:19
I just ran into the same issue with a freshly installed Ubuntu 16.04 LTS and ReText 7.0.0 via pip. Also Ctrl+Q does not work either.

Unfortunately the provided workaround to run ReText with that environment variable given

    $ UBUNTU_MENUPROXY=0 retext

does not work for me. Any suggestions?

**Comment by mitya57** [comment] 2017-03-15 14:03
@MrksKwsnck The fixed Qt packages will be in the main Ubuntu repository very soon. In the mean time you can use [ppa:ci-train-ppa-service/2569](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/2569).

**Comment by WellRedPandit** [comment] 2017-06-28 00:22
@MrksKwsnck @mitya57 -- just wanted to confirm that some shortcuts do work (e.g. Ctrl+O, Ctrl+Z) and some don't (e.g. Ctrl+B, Ctrl+F). UBUNTU_MENUPROXY=0 does not help. i'm on 16.04.2 and everything's up to date.

looks like we are not alone though: [Texmaker Shortcuts not working on Ubuntu 16.04](https://askubuntu.com/questions/786280/texmaker-shortcuts-not-working-on-ubuntu-16-04)
i tried what they suggested (sudo apt-get remove appmenu-qt5). no effect whatsoever.

fyi: ppa:ci-train-ppa-service/2569 throws a 404

**Comment by mitya57** [comment] 2018-07-13 19:37
This bug was fixed in Ubuntu 16.04 Qt packages, see [LP: #1380702](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1380702).

If it still happens for someone then please file a new bug.

**Closed by mitya57** 2018-07-13 19:37 UTC
