### ISSUE TITLE
No stylesheet when exporting to HTML

### ISSUE THREAD

**Issue by pagiraud** [retext-project/retext#468] opened 2019-09-01 20:16 UTC
Hi,
I have several stylesheets. All are displayed in the live preview panel and Retext tries to use them as far as it can when exporting to PDF or even to ODT. But when I'm exporting to HTML, the stylesheet is not used at all : not even loaded in the sourcecode.

My current config :

    [General]
    highlightCurrentLine=true
    lineNumbersEnabled=true
    livePreviewByDefault=true
    recentFileList=**********
    spellCheck=true
    styleSheet=/home/********/.config/ReText project/style.css
    useWebKit=true

The header of a generated HTML file:

    <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="generator" content="ReText 7.0.4">
    <title>presentation_generale</title>
    </head>

**Comment by mitya57** [comment] 2019-09-02 14:04
Hi!

I would say that it is by design. The stylesheet is a local file on your machine. If I add `<link rel="stylesheet" href="path/to/file.css">` to the generated file, and then you copy that HTML file to a remote server, the link will become dead.

However, there is a workaround. If you place the CSS file alongside your Markdown file and with the same basename (e.g.: `mydocument.mkd`, `mydocument.css`) then ReText will include the link.

Does that suit you?

**Comment by pagiraud** [comment] 2019-09-02 20:42
Hi,
I get your point. Nevertheless, it is quite strange that the style gets used when exporting to some formats and not others. Maybe a solution (optional ?) would be to include the CSS code from the stylesheet directly in the HTML file, using `<style></style>` tags in the header, as this is something similar that is done with PDF and ODT.
Your solution doesn't quite fit my needs, as I have dozens ´.md´ files spread across a hierarchy of directories. But don't worry, I'll deal with it. For now, this is not a deal breaker. ;)

**Comment by mitya57** [comment] 2019-09-06 15:14
OK, the stylesheet will be included now. Can you test master branch?

**Closed** 2019-09-06 15:13 UTC

**Comment by pagiraud** [comment] 2019-09-07 08:31
That's perfect! Thanks a lot.
