### ISSUE TITLE
Missing icons and RuntimeErrors

### ISSUE THREAD

**Issue by nyov** [retext-project/retext#199] opened 2016-03-23 18:09 UTC
It seems I'm missing some icons. How might I get the missing icons?

![2016-03-23_180122_940759362](https://cloud.githubusercontent.com/assets/438293/13995514/5f540606-f121-11e5-9505-b58ebe1c406e.png)

On debian Linux. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793934#36 says I might install some packages, but they are already installed:

> - adwaita-icon-theme
> - gsettings-desktop-schemas
> - gir1.2-glib-2.0

Also, testing the current master branch, I get this endless error:
```pytb
$ ./retext.py 
Using configuration file: /home/nyov/.config/ReText project/ReText.conf
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/retext.git/ReText/converterprocess.py", line 62, in _converter_process_func
    converted = current_markup.convert(job['text'])
AttributeError: 'MarkdownMarkup' object has no attribute 'convert'
Traceback (most recent call last):
  File "/tmp/retext.git/ReText/tab.py", line 226, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/tmp/retext.git/ReText/converterprocess.py", line 138, in get_result
    status, converted = receiveObject(self.conn)
  File "/tmp/retext.git/ReText/converterprocess.py", line 27, in receiveObject
    size = struct.unpack('I', sizeBuf)[0]
struct.error: unpack requires a bytes object of length 4
Traceback (most recent call last):
  File "/tmp/retext.git/ReText/tab.py", line 226, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/tmp/retext.git/ReText/converterprocess.py", line 134, in get_result
    raise RuntimeError('No ongoing conversion')
RuntimeError: No ongoing conversion
Traceback (most recent call last):
  File "/tmp/retext.git/ReText/tab.py", line 226, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/tmp/retext.git/ReText/converterprocess.py", line 134, in get_result
    raise RuntimeError('No ongoing conversion')
RuntimeError: No ongoing conversion
Traceback (most recent call last):
  File "/tmp/retext.git/ReText/tab.py", line 226, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/tmp/retext.git/ReText/converterprocess.py", line 134, in get_result
    raise RuntimeError('No ongoing conversion')
RuntimeError: No ongoing conversion
[...]
Traceback (most recent call last):
  File "/tmp/retext.git/ReText/tab.py", line 226, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "/tmp/retext.git/ReText/converterprocess.py", line 134, in get_result
    raise RuntimeError('No ongoing conversion')
RuntimeError: No ongoing conversion
Traceback (most recent call last):
  File "/usr/lib/python3.4/weakref.py", line 582, in _exitfunc
    f()
  File "/usr/lib/python3.4/weakref.py", line 506, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/tmp/retext.git/ReText/converterprocess.py", line 109, in on_finalize
    sendObject(conn_parent, {'command':'quit'})
  File "/tmp/retext.git/ReText/converterprocess.py", line 35, in sendObject
    sock.sendall(sizeBuf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by nyov** [comment] 2016-03-23 18:19
Ah, solved the icon issue by setting "Adwaita" as the icon theme name in prefs.

**Comment by mitya57** [comment] 2016-03-24 06:58
> It seems I'm missing some icons.

This can have many different reasons. Which desktop environment are you using? What is the value of `$XDG_CURRENT_DESKTOP` environment variable? Which mechanism does your environment use to store the icon theme settings? Do GTK+ applications work?

> Also, testing the current master branch, I get this endless error:

For current master branch you also need the current master branch of https://github.com/retext-project/pymarkups (this will be soon released as 2.0). I have now adjusted the code to print a better error message.

**Comment by nyov** [comment] 2016-03-24 13:24
Running awesome WM, and parts of the GTK2/3 DE, depending on what the software needs.
That currently includes `gsettings-desktop-schemas` and the other listed potential dependencies above.
GTK2 and 3 apps that I have installed worked okay so far, though I don't have a truckload of them.

I haven't set `$XDG_CURRENT_DESKTOP`, running my WMs from `.xinitrc`/`.Xsession` script.
I have set my default GTK2 themes using `~/.gtkrc-2.0`'s `gtk-icon-theme-name` setting and my default GTK3 themes using `$XDG_CONFIG_HOME/gtk-3.0/settings.ini`.
(As explained in https://wiki.archlinux.org/index.php/GTK%2B#Configuration )
The GTK apps I used so far seem to obey those settings.

**Comment by nyov** [comment] 2016-03-24 13:34
But as noted above, I solved the icons by manually setting the theme name. That's a viable solution to me, and as the other problem seems "fixed", you may close the issue. (Thanks! Why would it catch and ignore that Exception in the first place though?)

**Comment by mitya57** [comment] 2016-03-26 20:34
> But as noted above, I solved the icons by manually setting the theme name.

That's only a workaround, but not a fix — such thing should work by default for as many users as possible…

Can you please run this code in a Python 3 console and tell me what it prints?

```python
>>> from gi.repository import Gio
>>> settings = Gio.Settings.new('org.gnome.desktop.interface')
>>> settings.get_string('icon-theme')
```

**Comment by nyov** [comment] 2016-03-26 22:39
```pytb
In [1]: from gi.repository import Gio
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b0f7737b88aa> in <module>()
----> 1 from gi.repository import Gio

ImportError: No module named 'gi'
```
Seems it's not listed as a needed package in the setup script. ;) Though it's there in my python2 install.
Neither does the debian package depend on `python3-gi`. Guess that solves it.
Works now after installing that package. Thanks for investigating!

**Comment by mitya57** [comment] 2016-03-26 22:49
Thanks!

That package is not a dependency, because it's only needed as a fallback for loading icons (when Qt's built-in methods and XSettings do not work).

Now I know it's not a bug in ReText, so closing this.

**Closed by mitya57** 2016-03-26 22:49 UTC
