### ISSUE TITLE
When export to html file, encoding of Chinese charactercs is not correct.

### ISSUE THREAD

**Issue by sharpbladepan** [retext-project/retext#188] opened 2016-01-22 15:43 UTC
All Chinese become ������. 
But if "View HTML source" is selected from the Edit menu, the characters are correct.
Tried to adjust encoding under the File menu, nothing changed.

**Comment by mitya57** [comment] 2016-01-25 14:32
Thanks for your bug report.

- Which ReText version are you using?
- Did you alter the default encoding in the configuration file?
- Can you please attach the wrong HTML file generated by ReText?

**Comment by Vdragon** [comment] 2016-02-29 15:08
I can't reproduce this issue in ReText 5.2.1 (using PyMarkups 0.6.3).

* Which encoding is used in your Markdown source file?

**Comment by mitya57** [comment] 2016-03-12 13:12
The original reporter doesn't respond, @Vdragon cannot reproduce this, so closing.

**Closed by mitya57** 2016-03-12 13:12 UTC
