### ISSUE TITLE
Whole file was suddenly emptied while editing

### ISSUE THREAD

**Issue by frantic1048** [retext-project/retext#234] opened 2016-09-08 06:36 UTC
While I'm editing a trival `.rst` file today, the whold editing area was suddenly emptied. And, I can not even ctrl+Z to recover. Then I noticed the file's size I was editing had become 0 Byte, seems the empty action was already saved.

**os:** Arch Linux latest
**retext:** 6.0.1
**retext pkgrel(for Arch Linux):** 2
**python-markups:** 2.0.0

I'm sorry I could just provide such information. We may keep an eye on this issue, to find the actual reason...

I'm trying to grep my /dev/sda now....·´¯`(>▂<)´¯`·.
nothing found ... ｡：ﾟ(｡ﾉω＼｡)ﾟ･｡

**Comment by mitya57** [comment] 2016-09-08 06:38
Do you have auto-save, or other non-default options enabled?

**Comment by frantic1048** [comment] 2016-09-08 07:46
Here is my `~/.config/ReText project/ReText.conf`

```
autoSave=true
editorFont=WenQuanYi Micro Hei Mono
editorFontSize=10
font=Source Han Sans SC
fontSize=12
lineNumbersEnabled=true
previewState=true
recentFileList=/home/frantic/doc/txt/interview/Cang Feng.rst, /home/frantic/doc/txt/\x8ba1\x534f\x6280\x672f\x90e8\x524d\x7aef\x7ec4/2014\x8ba1\x534f\x6280\x672f\x90e8\x524d\x7aef\x7ec4\x6298\x817e\x8ba1\x5212.md, /home/frantic/code/daily/use/\x5e38\x7528shell\x547d\x4ee4.md
restorePreviewState=true
saveWindowGeometry=true
spellCheckLocale=en_US
useWebKit=true
windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\x30\0\0\x1\r\0\0\x6+\0\0\x4Y\0\0\0\x32\0\0\x1\x1f\0\0\x6)\0\0\x4W\0\0\0\0\0\0\0\0\a\x80)
```

**Comment by frantic1048** [comment] 2016-09-08 08:55
According to the situation, I think it should be related to auto-save feature.

**Comment by mitya57** [comment] 2016-09-13 10:08
Do you know a way to reproduce it? Or did it only happen once?

I spent some time with auto save mode enabled, and could not reproduce it…

**Comment by mitya57** [comment] 2016-10-21 19:38
@frantic1048 Do you still get this bug? Does it happen reproducibly?

**Comment by frantic1048** [comment] 2016-10-22 05:15
@mitya57 I have not reproduced it these days. >_<

**Comment by mitya57** [comment] 2016-10-22 05:25
As I can’t reproduce it myself too, closing.

**Closed by mitya57** 2016-10-22 05:25 UTC
