### ISSUE TITLE
Prevent the $posmapmarker$ appearing in code blocks

### ISSUE THREAD

**Issue by xgouchet** [retext-project/retext#299] opened 2017-07-21 08:52 UTC
When creating a code block, eg : 

    ```java
    int i = 0;
    
    i++;
    ```

The preview will contain $posmapmarker$ text for each blank line : 

```
int i = 0;

$posmapmarker$2

i++;
```

Note that this is only an issue with the live preview : exported html doesn't have this issue.

**Comment by mitya57** [comment] 2017-07-21 09:07
I cannot reproduce this. Which other Markdown extensions you have enabled?

There is a [special processor](https://github.com/retext-project/retext/blob/master/ReText/mdx_posmap.py#L53) that should clean these markers, maybe some other extension prevents it from working?

**Comment by xgouchet** [comment] 2017-07-21 09:23
I'm using the Markdown format, with the Chromium WebEngine renderer. 

Indeed, it comes from an extension : `markdown.extensions.codehilite`. If I remove it the problem disapears

**Comment by mitya57** [comment] 2017-07-21 16:12
I pushed a fix, but I don’t really like it as it doesn’t guarantee we won’t have the same bug with other extensions. @Griffon26 maybe you have any better ideas?

**Closed** 2017-07-21 16:11 UTC

**Comment by Griffon26** [comment] 2017-07-21 18:33
If the posmapmarker is included in a HTML fragment, but not modified (like with a fenced code block), it will have been expanded to a line containing '$posmapmarker$123', followed by one empty line.
But in this case our posmapmarker has been modified by another preprocessor plugin (codehilite).

I think we have to choose a heuristic for matching whatever the posmapmarker is turned into *even if* they it has been preprocessed by another preprocessor plugin.

Let's say we match everything from the beginning of the line containing $posmapmarker$ upto and including the newline of the next line. Can you come up with a scenario where that would give the wrong output?

**Comment by mitya57** [comment] 2017-07-21 18:41
Good idea but still not ideal.

I.e. in case of codehilite the dollar sign and the digits can have some special meaning for the highlighter (i.e. it has in Perl or PHP), so after it encounters that it will color the following code differently, or mark it as syntax error.
