### ISSUE TITLE
sudo pip3 install retext failed on Linux mint 18.3

### ISSUE THREAD

**Issue by SweRavn** [retext-project/retext#365] opened 2018-05-02 18:12 UTC
sudo pip3 install ReText
The directory '/home/ravn/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ravn/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ReText
  Downloading https://files.pythonhosted.org/packages/2a/ba/581591a8a8d48d02236b57633ae5f55247424885e143fe1d21fba904a1ed/ReText-7.0.1.tar.gz (266kB)
    100% |████████████████████████████████| 276kB 3.2MB/s 
  Ignoring PyQt5: markers 'platform_system == "Windows"' don't match your environment
  Ignoring PyQt5: markers 'platform_system == "Darwin"' don't match your environment
Requirement already satisfied: docutils in /usr/lib/python3/dist-packages (from ReText) (0.12)
Collecting Markdown (from ReText)
  Downloading https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 2.3MB/s 
Collecting Markups>=2.0 (from ReText)
  Downloading https://files.pythonhosted.org/packages/87/f9/3acf0b6d96564108ba96f06e6ccdc7722ade412c90c641d5160c175595cb/Markups-2.0.1.tar.gz
Collecting pyenchant (from ReText)
  Downloading https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 2.3MB/s 
Requirement already satisfied: Pygments in /usr/lib/python3/dist-packages (from ReText) (2.1)
Requirement already satisfied: chardet>=2.3 in /usr/lib/python3/dist-packages (from ReText) (2.3.0)
Installing collected packages: Markdown, Markups, pyenchant, ReText
  Running setup.py install for Markups ... done
  Running setup.py install for pyenchant ... done
  Running setup.py install for ReText ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm4lxb5j/ReText/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8r_jywj9/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sm4lxb5j/ReText/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8r_jywj9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-sm4lxb5j/ReText/

**Comment by mitya57** [comment] 2018-05-02 18:17
Try installing the latest version from git — the issue should be fixed there:

    pip3 install --user https://github.com/retext-project/retext/archive/master.zip#egg=ReText

I do not recommend running `pip3` as root, as it can mess up with your system Python modules.

The issue is fixed in git and the fix will be present in the next release.

**Closed by mitya57** 2018-05-02 18:17 UTC
